name: CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Git checkout (merge)
      uses: actions/checkout@v3
      if: github.event_name != 'pull_request'
      with:
        fetch-depth: 0

    - name: Git checkout (PR)
      uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        # see: https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'sbt'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.nvm
          ~/work/scommons-material-ui/scommons-material-ui/codegen/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-material-ui/scommons-material-ui/codegen/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-material-ui/scommons-material-ui/core/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-material-ui/scommons-material-ui/core/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-material-ui/scommons-material-ui/test/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-material-ui/scommons-material-ui/test/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-material-ui/scommons-material-ui/showcase/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-material-ui/scommons-material-ui/showcase/target/scala-2.13/scalajs-bundler/test/package-lock.json
        key: ${{ runner.os }}-node_modules-cache-v3-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-cache-v3-

    - name: Run tests
      run: sbt coverage test && sbt coverageAggregate coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Extract Tag Name
      run: echo "TAG_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      if: ${{ startsWith(github.ref, 'refs/tags') }}

    - name: Publish SNAPSHOT
      run: sbt clean publish
      if: ${{ !github.event.pull_request && env.TAG_NAME == '' }}
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Publish RELEASE
      run: echo "TAG_NAME=$TAG_NAME" && echo "github.ref=${{ github.ref }}"
      if: ${{ env.TAG_NAME != '' }}
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
